  
language: node_js
git:
  depth: 3
node_js:
  - "node"
install: npm install
services:
  - mysql
script:
  - cd web
  - npm install
  - npm run test
  - npm run build:client
  - cd ..
  - cd api
  - npm i
  - npx sequelize db:migrate
  - npm run test
cache:
  directories:
    - node_modules
notifications:
  email: false
env:
  - NODE_ENV=test
before_install:
  - mysql -e 'CREATE DATABASE ecommerce;'
after_failure:
  - cat  /home/travis/.npm/_logs/*
