version: "3"

services:
  api:
    image: api:latest
    build: api/
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web

  web:
    build: web/
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "ecommerce"
      MYSQL_ROOT_PASSWORD: "password"
