version: "3"

services:
  api:
    image: api:latest
    build: api/
    command: bash -c 'ls && ./wait-for.sh db:3306 -- npm start'
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build: web/
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "ecommerce"
      MYSQL_ROOT_PASSWORD: "password"
